services:
  postgres:
    image: 'postgres:15.3'
    container_name: "cloud-postgres"
    restart: on-failure
    environment:
      - 'POSTGRES_DB=cloudstorage'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
