services:
  postgres:
    image: 'postgres:15.3'
    container_name: "cloud-postgres"
    restart: on-failure
    environment:
      - 'POSTGRES_DB=cloudstorage'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address :9090
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio-data:/data
    ports:
      - "9090:9090"
      - "9000:9000"

  mongo:
    image: mongo:7.0.16-jammy
    container_name: mongo-cloud
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cloudstorage
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    depends_on:
      - minio
      - postgres

volumes:
  postgres_data:
  minio-data:
  mongo_data: