services:
  postgres:
    image: 'postgres:15.3'
    container_name: "cloud-postgres"
    restart: on-failure
    environment:
      - 'POSTGRES_DB=cloudstorage'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address :9090
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio-data:/data
    ports:
      - "9090:9090"
      - "9000:9000"

volumes:
  postgres_data:
  minio-data: