services:
  postgres:
    image: 'postgres:15.3'
    container_name: "cloud-postgres"
    restart: on-failure
    environment:
      - 'POSTGRES_DB=cloudstorage'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: 'redis:7.4.2-alpine'
    container_name: "jwt-redis"
    restart: on-failure
    command: redis-server --appendonly yes --requirepass postgres
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
volumes:
  postgres_data:
  redis_data: